[package]
name = "tetris2"
version = "0.1.0"
edition = "2021"

[dependencies]
piston = "0.53.0"
piston2d-graphics = "0.41.0"
pistoncore-glutin_window = "0.69.0"
piston2d-opengl_graphics = "0.79.0"
transpose = "0.2.1"
